[package]
name = "hex_arch_repositories"
version = "0.3.14"
authors = ["Trey Lowerison <19714082+tlowerison@users.noreply.github.com>"]
edition = "2021"

[dependencies]
proc_macros = { path = "./proc-macros", package = "hex_arch_repositories_proc_macros" }
